"""empty message

Revision ID: ae1e5802d882
Revises: 
Create Date: 2023-03-16 22:27:28.909883

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ae1e5802d882'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navak_education_degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navak_work_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('navak_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserName', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=102), nullable=False),
    sa.Column('FirstName', sa.String(length=64), nullable=False),
    sa.Column('LastName', sa.String(length=64), nullable=False),
    sa.Column('FatherName', sa.String(length=64), nullable=False),
    sa.Column('BirthDay', sa.Date(), nullable=True),
    sa.Column('MeliCode', sa.String(length=32), nullable=True),
    sa.Column('BirthLocation', sa.String(length=64), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=11), nullable=True),
    sa.Column('EmergencyPhone', sa.String(length=11), nullable=True),
    sa.Column('Address', sa.String(length=256), nullable=True),
    sa.Column('Education', sa.Integer(), nullable=True),
    sa.Column('StaffCode', sa.Integer(), nullable=False),
    sa.Column('ContractType', sa.String(length=64), nullable=True),
    sa.Column('StartContract', sa.Date(), nullable=False),
    sa.Column('EndContract', sa.Date(), nullable=False),
    sa.Column('WorkPosition', sa.Integer(), nullable=False),
    sa.Column('VacationHourTotal', sa.Float(), nullable=False),
    sa.Column('VacationHourTaken', sa.Float(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('Married', sa.Boolean(), nullable=False),
    sa.Column('Children', sa.Integer(), nullable=False),
    sa.Column('BaseSalary', sa.Integer(), nullable=False),
    sa.Column('Created_Time', sa.DateTime(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Education'], ['navak_education_degree.id'], ),
    sa.ForeignKeyConstraint(['WorkPosition'], ['navak_work_position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('navak_employee')
    op.drop_table('navak_work_position')
    op.drop_table('navak_education_degree')
    # ### end Alembic commands ###
