"""empty message

Revision ID: d29c431f973b
Revises: ae1e5802d882
Create Date: 2023-03-16 22:30:57.899153

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd29c431f973b'
down_revision = 'ae1e5802d882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navak_roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('RoleName', sa.String(length=64), nullable=True),
                    sa.Column('RoleDescription', sa.String(length=256), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('navak_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=False),
                    sa.Column('password', sa.String(length=102), nullable=False),
                    sa.Column('FullName', sa.String(length=102), nullable=True),
                    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
                    sa.Column('Active', sa.Boolean(), nullable=True),
                    sa.Column('ProfileImage', sa.String(length=256), nullable=False),
                    sa.Column('UserSignature', sa.String(length=256), nullable=True),
                    sa.Column('Usertag', sa.String(length=128), nullable=True),
                    sa.Column('PublicKey', sa.String(length=36), nullable=False),
                    sa.Column('UserRole', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['UserRole'], ['navak_roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('PublicKey'),
                    sa.UniqueConstraint('Usertag'),
                    sa.UniqueConstraint('username')
                    )
    with op.batch_alter_table('navak_employee', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'navak_education_degree', ['Education'], ['id'])
        batch_op.create_foreign_key(None, 'navak_work_position', ['WorkPosition'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navak_employee', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('navak_users')
    op.drop_table('navak_roles')
    # ### end Alembic commands ###
